/**
 * Alfaseguros' inbound number pool. The "customer" of any call is always the
 * other end — `from_number` for inbound, `to_number` for outbound.
 */
export const ALFASEGUROS_NUMBERS: ReadonlySet<string> = new Set([
  "351215832338",
  "351210270858",
  "351210270860",
  "351210270869",
]);

/**
 * Ringover user_ids to exclude from analysis. Empty now: Hélio Vazão (the Vida
 * coordinator) was previously excluded, but the V2 supervisor analyses the Vida
 * team, so his calls are included too.
 */
export const VIDA_AGENT_IDS: ReadonlySet<number> = new Set([]);

/** Minimum length of `note` (Ringover AI summary) to be worth analyzing. */
export const MIN_NOTE_LENGTH = 50;

/** Ringover's `note` field always ends with this generated-by tail; strip before sending to the LLM. */
export const GENERATED_BY_AI_PATTERN = /Generated by AI[\s\S]*$/g;
