import { describe, expect, it } from "vitest";
import {
  digitsOnly,
  getAgentUserId,
  isAnalyzable,
  pickCustomerNumber,
  stripGeneratedByAI,
} from "./filter.js";
import type { RingoverCall } from "./types.js";

const ALFA = "351215832338";

function call(overrides: Partial<RingoverCall> = {}): RingoverCall {
  return {
    cdr_id: 1,
    is_answered: true,
    note: "Cliente ligou para pedir cotação TVDE. Operador apresentou opções e enviou simulação por email. Cliente vai pensar.",
    direction: "in",
    from_number: "351911234567",
    to_number: ALFA,
    user: { user_id: 100, firstname: "Marina", lastname: "X", team_id: 17922751 },
    ...overrides,
  };
}

describe("stripGeneratedByAI", () => {
  it("removes the trailing 'Generated by AI...' marker", () => {
    expect(
      stripGeneratedByAI("Cliente pediu cotação.\nGenerated by AI from a transcript of the call."),
    ).toBe("Cliente pediu cotação.");
  });

  it("leaves notes without the marker untouched", () => {
    expect(stripGeneratedByAI("Cliente pediu cotação.")).toBe("Cliente pediu cotação.");
  });
});

describe("digitsOnly", () => {
  it("strips formatting characters", () => {
    expect(digitsOnly("+351 911 234 567")).toBe("351911234567");
    expect(digitsOnly("00351-911234567")).toBe("00351911234567");
  });
  it("handles null/undefined safely", () => {
    expect(digitsOnly(null)).toBe("");
    expect(digitsOnly(undefined)).toBe("");
  });
});

describe("pickCustomerNumber", () => {
  it("returns from_number for inbound calls to the Alfaseguros pool", () => {
    expect(pickCustomerNumber({ direction: "in", from_number: "351911234567", to_number: ALFA, contact_number: null }))
      .toBe("351911234567");
  });

  it("returns to_number for outbound calls from the Alfaseguros pool", () => {
    expect(pickCustomerNumber({ direction: "out", from_number: ALFA, to_number: "351911234567", contact_number: null }))
      .toBe("351911234567");
  });

  it("falls back to direction when neither end is in the pool", () => {
    expect(pickCustomerNumber({ direction: "in", from_number: "351919999999", to_number: "351918888888", contact_number: null }))
      .toBe("351919999999");
  });

  it("returns null when both ends are empty", () => {
    expect(pickCustomerNumber({ direction: "in", from_number: null, to_number: null, contact_number: null }))
      .toBeNull();
  });
});

describe("getAgentUserId", () => {
  it("prefers nested user.user_id", () => {
    expect(getAgentUserId(call({ user: { user_id: 42 }, user_id: 99 }))).toBe(42);
  });
  it("falls back to top-level user_id", () => {
    expect(getAgentUserId(call({ user: null, user_id: 7 }))).toBe(7);
  });
  it("returns null when neither is set", () => {
    expect(getAgentUserId(call({ user: null, user_id: null }))).toBeNull();
  });
});

describe("isAnalyzable", () => {
  it("accepts a typical answered call with a real note from a Não Vida agent", () => {
    expect(isAnalyzable(call())).toBe(true);
  });

  it("rejects unanswered calls", () => {
    expect(isAnalyzable(call({ is_answered: false }))).toBe(false);
  });

  it("rejects calls whose note is shorter than 50 chars after stripping the AI tail", () => {
    expect(isAnalyzable(call({ note: "Cliente desligou.\nGenerated by AI from a transcript." }))).toBe(false);
  });

  it("rejects calls whose note is missing entirely", () => {
    expect(isAnalyzable(call({ note: null }))).toBe(false);
  });

  it("now accepts the former Vida exclusion (VIDA_AGENT_IDS is empty)", () => {
    expect(isAnalyzable(call({ user: { user_id: 23185416, firstname: "Hélio", lastname: "Vazão" } }))).toBe(true);
  });
});
