import {
  ALFASEGUROS_NUMBERS,
  GENERATED_BY_AI_PATTERN,
  MIN_NOTE_LENGTH,
  VIDA_AGENT_IDS,
} from "./constants.js";
import type { RingoverCall } from "./types.js";

/** Strip the `Generated by AI...` trailer Ringover appends to every AI note. */
export function stripGeneratedByAI(note: string): string {
  return note.replace(GENERATED_BY_AI_PATTERN, "").trim();
}

/** Normalize a phone string to digits-only. */
export function digitsOnly(phone: string | null | undefined): string {
  if (!phone) return "";
  return phone.replace(/\D/g, "");
}

/**
 * Pick the customer's phone number from a call: whichever end is NOT in the
 * Alfaseguros number pool. Falls back to the non-empty end if neither matches.
 */
export function pickCustomerNumber(call: Pick<RingoverCall, "direction" | "from_number" | "to_number" | "contact_number">): string | null {
  const from = digitsOnly(call.from_number);
  const to = digitsOnly(call.to_number);
  const fromIsAlfa = from !== "" && ALFASEGUROS_NUMBERS.has(from);
  const toIsAlfa = to !== "" && ALFASEGUROS_NUMBERS.has(to);

  if (fromIsAlfa && !toIsAlfa) return to || null;
  if (toIsAlfa && !fromIsAlfa) return from || null;

  // Neither or both ends are in the pool — fall back to direction hint.
  if (call.direction === "in" || call.direction === "inbound") return from || null;
  if (call.direction === "out" || call.direction === "outbound") return to || null;

  // Last resort: contact_number, then whichever end is non-empty.
  const contact = digitsOnly(call.contact_number);
  return contact || from || to || null;
}

/** Resolve the agent's user_id for a call, regardless of where it is on the payload. */
export function getAgentUserId(call: RingoverCall): number | null {
  if (call.user && typeof call.user.user_id === "number") return call.user.user_id;
  if (typeof call.user_id === "number") return call.user_id;
  return null;
}

/**
 * Whether a Ringover call carries enough signal to be analyzed.
 * Filter rules per HANDOVER §1 (already implemented in grouping):
 *   - is_answered === true
 *   - note exists and has >= 50 characters of usable content (after stripping "Generated by AI...")
 *   - agent is not on the Vida team (Hélio Vazão et al.)
 */
export function isAnalyzable(call: RingoverCall): boolean {
  if (call.is_answered !== true) return false;
  const note = call.note ? stripGeneratedByAI(call.note) : "";
  if (note.length < MIN_NOTE_LENGTH) return false;
  const agentId = getAgentUserId(call);
  if (agentId != null && VIDA_AGENT_IDS.has(agentId)) return false;
  return true;
}
